### ISSUE TITLE
Id cities

### ISSUE THREAD

**Issue by tghelere** [magnobiet/laravel-states-cities-brazil#1]
Boa tarde
Gostaria de saber por que os ids das cidades são esses números grandes.
Terei algum problema se não setar o id no seeder e deixar que ele inicie pelo id 1?

Abraço

**Comment by magnobiet** [comment]
O `id` é igual ao código do município fornecido pelo IBGE.

Pode mudar no seu projeto caso queira, basta ajustar teu seed.

**Comment by tghelere** [comment]
Suspeitei desde o principio! haha

Muito obrigado, tanto pela resposta rápida quanto pelo código.
Abraço
