### ISSUE TITLE
Erro de namespace ao utilizar em projeto Laravel  8+

### ISSUE THREAD

**Issue by ropehapi** [magnobiet/laravel-states-cities-brazil#2]
### O Problema
Ao seguir o processo de instalação descrito na documentação rodando os comandos `Target class [CitiesTableSeeder] does not exist.`, obtemos um erro `Target class [CitiesTableSeeder] does not exist.`.

### A causa
Isso acontece por conta de uma incompatibilidade de namespaces que existe entre o Laravel 6 (Versão na qual essa biblioteca foi desenvolvida), e as versões acima do Laravel 8.

### Soluções
se você quiser resolver o problema atualizando o projeto, [aqui está um link](https://laracasts.com/discuss/channels/code-review/target-class-productseeder-does-not-exist) de uma discussão onde se resolve esse problema.

Caso opte por uma solução mais fácil, que dispensa a atualização de todo o projeto, o que pode te poupar dor de cabeça, segue um passo a passo do que pode ser feito, que resolveu a situação para mim.

- Apague os dois seeders que você importou para dentro do seu projeto.
- Crie seeders iguais através dos comandos `php artisan make:seed CitiesTableSeeder` e `php artisan make:seed StatesTableSeeder`.
- Copie os métodos run de cada seeder original para os recém criados.
- Chame os seeders criados dentro do método run na `DatabaseSeeder` da seguinte maneira:
  - `$this->call([StatesTableSeeder::class, CitiesTableSeeder::class,]);`
- Não se esqueça de importar o facade DB nos seus seeders através do `use Illuminate\Support\Facades\DB;`
- Rode o comando `php artisan db:seed` e divirta-se.

De qualquer maneira, espero ter ajudado aqueles que estão enfrentando o mesmo problema. Qualquer dúvida entrem em contato comigo.

**Comment by magnobiet** [comment]
@ropehapi muito obrigado por reportar.

Fiz uma atualização nas `seeds` incluindo o `namespace`, rodei e me pareceu estar tudo OK.

Caso tenha mais sugestões seus PRs serão bem vindos.

Espero poder ter ajudado.

**Comment by ropehapi** [comment]
Tamo junto, meu amigo. Gostaria muito de ter feito um PR corrigindo a situação mas como eu estava sem tempo acabou que optei por apenas abrir uma issue ensinando a corrigir mesmo. Mas o que importa é que no final deu tudo certo e você corrigiu. Muito obrigado.
